
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module rippleCarryAdder_test(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire [63:0] a_d;
wire [63:0] b_d;

reg  [63:0] a_q;
reg  [63:0] b_q; 

wire [63:0] out_d;
reg [63:0] out_q;

wire        cout_d;
reg         cout_q;

wire [3:0]  add_d;
reg  [3:0]  add_q;



//=======================================================
//  Structural coding
//=======================================================

ram_1pt	RAMA (
	.address ( add_q ),
	.clock ( MAX10_CLK1_50 ),
	.data  ( /* open */    ),
	.wren  ( 1'b0          ),
	.q     ( a_d           )
	);

ram_1pt	RAMB (
	.address ( add_q ),
	.clock ( MAX10_CLK1_50 ),
	.data  ( /* open */    ),
	.wren  ( 1'b0          ),
	.q     ( b_d           )
	);

ram_1pt	RAMC (
	.address ( add_q ),
	.clock ( MAX10_CLK1_50 ),
	.data  ( out_q         ),
	.wren  ( 1'b1          ),
	.q     ( /* open */    )
	);
	
rippleCarryAdder #(
	.Nbits(64), 
	.signd(0)
	) u_RCA (
	.a(a_q),
	.b(b_q),
	.cin(1'b0),
	.sum(out_d),
	.overflow(cout_d)
	);

always @(posedge MAX10_CLK1_50) begin

	a_q    <= a_d;
	b_q    <= b_d;
	out_q  <= out_d;
	cout_q <= cout_d;
	add_q  <= add_d + 1'b0001;

end

endmodule
